### ISSUE TITLE
Can it be used in Spring Cloud?

### ISSUE THREAD

**Issue by malafeev** [OpenFeign/feign-opentracing#10]
Spring Cloud provides own annotation based approach:

```java
import org.springframework.cloud.netflix.feign.FeignClient;
import org.springframework.stereotype.Component;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Component
@FeignClient(value = "rest-service-1", fallback = StoreClientFallback.class)
public interface StoreClient {

    @RequestMapping(method = RequestMethod.GET, value = "/")
    String get();

}
```

Usage:
```java
@EnableFeignClients
@RestController
@SpringBootApplication
public class ServiceApp2 {
 
 @Autowired
 private StoreClient storeClient;

  @GetMapping("/")
  public String index() {
    return storeClient.get();
  }
}
```

From README it is not clear how in this case instrumentation will happen?

**Comment by pavolloffay** [comment]
Directly using `org.springframework.cloud.netflix.feign.FeignClient` probably not. You would have to add some spring integration code.

**Comment by malafeev** [comment]
hm, I'm trying  https://github.com/opentracing-contrib/meta/issues/29 option 2.
But adding just dependency on `feign-opentracing` is not working.
I need kind of glue.

**Comment by pavolloffay** [comment]
Yes it needs a glue, all of "raw" instrumentations will need it (auto-configurations, maybe something more)
